---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# eads

<!-- badges: start -->
<!-- badges: end -->

The goal of `eads` is to provide local data users access to both canned and custom data tables at a variety of [Census geographies]() and [spatial extents](). This is a joint project of the [SLU openGIS](https://slu-opengis.github.io) effort and the [St. Louis Regional Data Alliance]().

## Installation

The development version from [GitHub](https://github.com/) with:

``` r
# install.packages("remotes")
remotes::install_github("slu-openGIS/eads")
```

## Regional Census Data


## What's in a Name?
`eads` is a reference to the [Eads Bridge](https://en.wikipedia.org/wiki/Eads_Bridge), the first bridge erected across the Mississippi River in St. Louis and an iconic landmark in the region. Like its namesake, `eads` provides a link between disparate corners of the region, ensuring we can paint a unified portrait with data instead of steel.

## Contributor Code of Conduct
Please note that this project is released with a [Contributor Code of Conduct](.github/CODE_OF_CONDUCT.md). By participating in this project you agree to abide by its terms.
